### ISSUE TITLE
betaリリース時、docs/changelogのURLがbeta用のものになっていない

### ISSUE THREAD

**Issue by Sayamame-beans** [anatawa12/AvatarOptimizer#1013]
https://github.com/anatawa12/AvatarOptimizer/blob/977f79bfbc1af20cbc2df68b7e65708e4f0f6d92/package.json#L15-L16

actionsで自動化した方が良さそう

**Comment by anatawa12** [comment]
やるならアンカーもつけちゃったほうが良さそうなのでそうする

**Comment by anatawa12** [comment]
vpm.json内のが治ってない
