### ISSUE TITLE
T&O がパーティクルシステムのSimgeMaterialのサブメッシュ指定を破壊してしまっている

### ISSUE THREAD

**Issue by ReinaS-64892** [anatawa12/AvatarOptimizer#1016]
[context](https://misskey.niri.la/notes/9selp11vhc)

パーティクルのShape の欄で、SkinndMeshRenderer か MeshRenderer を選択したのち、SimgelMaterial を使用すると、特定のサブメッシュに限定したパーティクルの発生範囲を指定することができ、
![image](https://github.com/anatawa12/AvatarOptimizer/assets/99442371/e0a8cc76-de9f-46e7-8fb8-f92ed28e0433)

それらを使用したパーティクルが 1.7.0-rc.1 の環境だと、自動マージスキンドメッシュによって対象となるレンダラーがマージされ、意図しないサブメッシュにパーティクルが発生するようになります。

簡易的な回避策としては...パーティクルから参照されていた場合マージしない。

正しく処理するなら、レンダラーをマージするとき、パーティクルから参照されているサブメッシュはマージ行わず、パーティクルのサブメッシュの指定を再割り当てすることが望ましいです。

**Comment by anatawa12** [comment]
マージしない扱いや、そもそも別用途の参照のときに困る可能性があるのでほかコンポーネントによる参照がある場合にマージしないという形にします
