### ISSUE TITLE
Port UnusedBonesByReferencesTool

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/AvatarOptimizer#103]
作者本人からの提案。 https://twitter.com/narazaka/status/1648978964977979397 

https://narazaka.booth.pm/items/3831781

**Comment by Narazaka** [comment]
> AvatarDescriptorにcomponentつけると実行されるとかは良さそうですね。(思想的に設定無しでやるのは避けてます。)
> Zlibですか。とりあえずissue立てます。

そんな感じで良さそうに思います。

なんならzlibですけど雑にAvatarOptimizerの方のライセンスで出してもらってかまわないので
