### ISSUE TITLE
Feature Request: Automatic Merge 機能で一番BlendShapeが多いものだけマージから除外するオプション

### ISSUE THREAD

**Issue by kazu0617** [anatawa12/AvatarOptimizer#1034]
自分がよく使ってるワークフローなのですが、BlendShapeの多いメッシュを統合してしまうと、総合的なパフォーマンスは下がる傾向にあるというのを良く聞きます。

例えば、Resoniteの最適化ガイドラインという記事があります。ここでは以下の通り記載があります。
> ブレンドシェイプが変わるたびに、メッシュ全体の頂点を再変換する必要があります。メッシュの大部分がブレンドシェイプの一部でない場合、そのパフォーマンスは無駄になります。
https://wiki.resonite.com/Optimization_Guidelines

そのため、「顔等々、アバター内にある最もBlendShape数の多いSkinnedMesh」と、それ以外のSkinnedMeshの2つで統合したいです。

現在のところは「AAO Merge SkinnedMesh」でそのように適用していますが、今回「Auto SkinnedMesh Merge」が実装されましたので、要望した次第になります。

**Comment by anatawa12** [comment]
自動 Merge Skined Mesh では BlendShape が(自動FreezeBlendShape後に)あるメッシュについてのみ結合する仕様となっていますが、それとは別にBlendShapeがあるメッシュ同士を結合する機能がほしいということでしょうか

**Comment by anatawa12** [comment]
自動 Merge Skined Mesh では BlendShape が(自動FreezeBlendShape後に)ないメッシュについてのみ結合する仕様となっていますが、それとは別にBlendShapeがあるメッシュ同士を結合する機能がほしいということでしょうか

BlendShapeに影響する頂点数が増えることによる各種実行負荷の影響は気にしています。

https://vpm.anatawa12.com/avatar-optimizer/beta/ja/docs/tutorial/basic-usage/
> BlendShape(シェイプキー)は頂点数とBlendShape数の積に比例して重くなる処理です。 そのため、BlendShapeの数が多い顔のメッシュを頂点数の多い体のメッシュと統合するとかえって重くなってしまうため、顔は別のままにするのを推奨しています。

**Comment by kazu0617** [comment]
> 自動 Merge Skined Mesh では BlendShape が(自動FreezeBlendShape後に)ないメッシュについてのみ結合する仕様となっていますが、それとは別にBlendShapeがあるメッシュ同士を結合する機能がほしいということでしょうか
> 
> BlendShapeに影響する頂点数が増えることによる各種実行負荷の影響は気にしています。
> 
> https://vpm.anatawa12.com/avatar-optimizer/beta/ja/docs/tutorial/basic-usage/
> 
> > BlendShape(シェイプキー)は頂点数とBlendShape数の積に比例して重くなる処理です。 そのため、BlendShapeの数が多い顔のメッシュを頂点数の多い体のメッシュと統合するとかえって重くなってしまうため、顔は別のままにするのを推奨しています。

あ…でしたら問題なさそうですね。
Blendshape Freezeの処理があるとは思いますが、その処理でBlendShapeを飛ばした後に統合してる感じです？それであれば完全にクローズします。
（自分の想定は服などはフリーズさせてBlendShapeを飛ばしたあと、一括でSkinnedMeshをマージさせて拭くとそれ以外にする…って認識でした。）

**Comment by anatawa12** [comment]
> Blendshape Freezeの処理があるとは思いますが、その処理でBlendShapeを飛ばした後に統合してる感じです？

はい。手動及び自動FreezeBlendShapeの後にAutoMergeSMRの処理が走るため、(自動)FreezeBlendShapeによってすべてのBlendShapeが削除されるメッシュもAutoMergeSMRの処理対象になります。

**Comment by kazu0617** [comment]
であれば想定通りっぽそうですね…！
大丈夫です。クローズします。
