### ISSUE TITLE
Remove Mesh by MaskがTTTと互換性がない

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/AvatarOptimizer#1037]
ドキュメントに書くか、対応してもらうためになんかしら準備する

**Comment by anatawa12** [comment]
Reinaちゃんと相談した感じ、APIがあればなんかできるかもとのこと

**Comment by anatawa12** [comment]
editmode previewの互換性ってどうしましょう @ReinaS-64892

(NDMFプレビューシステムに移行した以降の話として)

**Comment by ReinaS-64892** [comment]
EditMode で互換性保つのだいぶきつくない...?
正直私はあきらめてるところではあるけど

**Comment by anatawa12** [comment]
諦めでいいか。なんかNDMF Mesh Previewの機能の一部としてなんかデータを受け渡せればできるかなとは一応思った感じ

**Comment by ReinaS-64892** [comment]
思ったのだけど、 #1177 にて実装された MeshRemovalProvider を使って #670 では UVの特定の座標に飛ばしてるけど
...これを NaN とか inf とかの絶対使われないであろう値に変えてそれを消してもらうような形にすれば、 RemoveMeshByMask のセーブデータに対して何かしなくても解決できる気がするけど...どうかな？

**Comment by ReinaS-64892** [comment]
あー...だとしても RemoveMeshByMask を無効化しないと ランダムな場所が破棄される可能性があるからそれはそれで対処が必要な気もするね
