### ISSUE TITLE
Trace And Optimize に Multi Pass Rendering の Material を変更するAnimationが削除される

### ISSUE THREAD

**Issue by dokkaikouze** [anatawa12/AvatarOptimizer#1040]
AnimationにSkinned Mesh RendererのMaterial SlotのMaterialを入れ替える処理が含まれていると該当する部分が削除されてしまう
入れ替えた後のMaterialは初期状態でAvatarに含まれておらず、Animationのみである

**Comment by anatawa12** [comment]
AnimationClipに指定したMaterial SlotのObject Animationが削除されるということだと認識し再現を試みましたが再現できませんでした。もう少し詳しく状況を教えて下さい。

**Comment by dokkaikouze** [comment]
問題発生状況の再現に成功したので、そのUnitypackageを同梱します
Unityの再生ボタンを押すとAnimationの内容が「$AvatarOptimizerClipLengthDummy$」に置き換わります

環境は
Unity2022.3.6f1
VRCSDK 3.5.2
AAO 1.7.0

https://drive.google.com/file/d/1tSbzmH7QMf2KnXKDTn3Yhoq-KKlCZ1NP/view?usp=sharing

**Comment by anatawa12** [comment]
ありがとうございます。複数マテリアルによるmulti pass renderingに対する対応が不足していました。修正します。
