### ISSUE TITLE
Migration要求のタイトルが英語のままっぽい

### ISSUE THREAD

**Issue by Sayamame-beans** [anatawa12/AvatarOptimizer#1046]
https://github.com/anatawa12/AvatarOptimizer/blob/8077ff7b1a164009f3f54dc076ad20b9d4129c8c/Editor/Migration/PrereleaseStateDetector.cs#L49

**Comment by anatawa12** [comment]
ぱっといいのが思いつかずにそうした記憶

**Comment by anatawa12** [comment]
あとはこのファイルはもうあんま弄るつもりがないのでwon'tfix
