### ISSUE TITLE
AAO TraceAndOptimize の OptimizeAnimator で motion=None の State を巻き込むと最適化前後で挙動が変わってしまう

### ISSUE THREAD

**Issue by whiteflare** [anatawa12/AvatarOptimizer#1048]
TraceAndOptimize  の Optimize Animator にチェックを入れている場合にて事象に遭遇しました。
処理した FX Animator は次の構成になっています。

- Layer0 : obj1 の active を true に設定するAnimClipを常時再生
- Layer1: int変数の値にて分岐し、値が 0 のときは motion=None、値が 1 および 2 のときは obj1 の active を false に設定する AnimClip を再生

なお各ステートの WriteDefault はオンとなっていて、TraceAndOptimize を付けていない場合は意図通り動作する AnimatorController でした。

上記の FX Animator を処理したとき、Layer1 の分岐が 1D BlendTree に変換されます。その BlendTree の motion は一部 None が含まれている状態です。
再生モードで動作確認すると、値が 0 のときにも obj1 が非アクティブになる挙動になりました。TraceAndOptimize する前は値0のとき obj1 はアクティブになっていたため、最適化前後で挙動が変化したことになります。

暫定対処として motion=None を使わずに空アニメーションクリップを設定しました。これにより BlendTree に変換された後も挙動が変わらないことを確認できました。

TraceAndOptimize  の仕様としては、次のどちらかであると嬉しいです。

1. motion=Noneを含むLayerはBlendTreeに変換しない
2. motion=NoneのステートをBlendTreeに変換するときには空のAnimationClipを生成して割り当てる

**Comment by anatawa12** [comment]
デフォルト側がnoneのときがまだだめ
