### ISSUE TITLE
Enter Play Mode の Reload Scene が無効な場合、RemoveMesh のプレビュー中に Play Mode に入ると全ポリゴンが消える

### ISSUE THREAD

**Issue by nekobako** [anatawa12/AvatarOptimizer#1049]
Enter Play Mode の Reload Scene が無効になっている場合、RemoveMesh 系コンポーネントをプレビューしたまま Play Mode に入ると、Box や Blendshape や Mask での範囲指定に関係なく全ポリゴンが消えるようです。

Unity 2022.3.6f1、AAO 1.7.0 で確認しました。

**Comment by anatawa12** [comment]
R/W Meshのエラーは出てきましたか？

<img width="319" alt="image" src="https://github.com/anatawa12/AvatarOptimizer/assets/22656849/f729bf10-fe29-46f7-bc9a-21806175cea3">

Reload Sceneが無効の状態で再現できませんでした。

**Comment by nekobako** [comment]
エラーは出てないですね・・

RemoveMesh の対象が T&O か MergeSMR で統合される場合は発生しないことが分かりました。
T&O の `スキンメッシュレンダラーを統合する` のチェックを外して MergeSMR からも除外すると発生するようです。

**Comment by anatawa12** [comment]
再現しました。AnimationModeの切り替え周りがなんかおかしそう...
