### ISSUE TITLE
MergeSMRにおいて発生する警告に対する説明を追加してほしい

### ISSUE THREAD

**Issue by Sayamame-beans** [anatawa12/AvatarOptimizer#1074]
https://vpm.anatawa12.com/avatar-optimizer/ja/docs/faq/#the-brightness-of-the-meshes-merged-with-aao-merge-skinned-mesh-component-is-different-from-other-meshes
にあるようなMA Mesh Settingsへの誘導などが、コンポーネントDocsにもチュートリアルにもない。

また、警告文にhow to fixが載ってないかも。(ref: https://misskey.niri.la/notes/9tcyrj3pk9)

**Comment by anatawa12** [comment]
how to fix、設定されてないって書いてるから設定すればいいじゃんって書かなくていいって認識してた

**Comment by Sayamame-beans** [comment]
まあ、how to fixでなくとも、何でそれが起きてるんだろうっていうのが(前提部分がドキュメントにしか無いから)伝わってないっぽい感じなので、何かしらの説明は足したいですね。

**Comment by anatawa12** [comment]
whyよきしない動作の恐れがあるを書くということですかね？
なぜ起きてるのかと、どのオブジェクトで起きてるかは書いてあるので

**Comment by Sayamame-beans** [comment]
んや、(それもあっても良さそうですが、)why未セットかですね。
まあドキュメント読んでって話ではあるんですけど、MergeSMRがRootBoneとかをセットしない旨はドキュメントかこのエラー文にしかなさそう?なので (…ここに書くんじゃなくて、MergeSMR側にwarnのhelpbox足せば良いのかな)

**Comment by anatawa12** [comment]
why未セットは手動で指定していないから以外あります？

**Comment by anatawa12** [comment]
localization層でいくらでも増やせるので必要であれば増やしてください

**Comment by Sayamame-beans** [comment]
> localization層でいくらでも増やせるので必要であれば増やしてください

Error/WarningのDescriptionってpoファイル側だけで増やせるのです? (流石にコード側の調整が必要?)

**Comment by anatawa12** [comment]
descriptionは<errorMessageId>:descriptionだかをついかすれはよかった。
詳細なキーは既存のやつ見てください

**Comment by Sayamame-beans** [comment]
了解です～
