### ISSUE TITLE
Asset Descriptionのdocsにおける、非破壊ツールである場合の対処法の記述が不十分?

### ISSUE THREAD

**Issue by Sayamame-beans** [anatawa12/AvatarOptimizer#1144]
> なお、非破壊ツールの場合については、正しくない実行順で処理が行われた場合に、Avatar Optimizerがコンポーネントを誤って削除してしまわないように、従来通りIVRCSDKPreprocessAvatarCallbackでコンポーネントを削除することを推奨します。

https://vpm.anatawa12.com/avatar-optimizer/ja/docs/developers/make-your-components-compatible-with-aao/
において、NDMF上でAAOより前に動いて消すという選択肢があるため、IVRCSDKPreprocessAvatarCallbackの手法しか載っていないのは不十分そうです。
(両方載せるか、軽く書いたうえで上記ページへのリンクに置き換えるなどの必要がありそう)

**Comment by anatawa12** [comment]
NDMFも`IVRCSDKPreprocessAvatarCallback`の一種ではあるので...という気持ち

**Comment by Sayamame-beans** [comment]
あー

**Comment by Sayamame-beans** [comment]
まあでも、こっちはそこまで自明ではなさそうな気もする? (自明なら上記リンクの方でも片方しか書いてなくて良いわけだし)

**Comment by anatawa12** [comment]
これもう解決かな

**Comment by Sayamame-beans** [comment]
Asset Descriptionの方を弄った記憶がない

**Comment by anatawa12** [comment]
リンクが違うので該当箇所を勘違いしてた
