### ISSUE TITLE
既存コンポーネントに対するComponent API操作でComponent used before initialization警告が発生する

### ISSUE THREAD

**Issue by Tatamo** [anatawa12/AvatarOptimizer#1205]
Unity Editor上でComponent APIが利用可能なコンポーネントを予め追加しておき、そのコンポーネントに対して操作を行うとInitializeメソッドを呼び出していないことに関して警告が発生します。

Component APIを用いて以下のようなNDMFプラグインを実装します。
* アバター内のメッシュを指定し、そのGameObjectに対してRemove Mesh In BoxのBoundingBoxを追加する
* プラグインは配布アセットにバンドルする

イメージとしては、アバター用アクセサリのメッシュ干渉対策としてアバター本体のメッシュを削除するというものです。

このとき、愚直な実装では、Generatingステップ中の処理でRemove Mesh In Boxが存在しなければ作成し、Initializeメソッドを呼び出します。その後Boxesに要素を追加します。
Remove Mesh In Boxが既に存在する場合、たとえばアクセサリを複数つけることで同一のプラグインの別のコンポーネントに対する処理の中で既に作成されているケース、未知のプラグインによってRemove Mesh In Boxが作成されているケース、もともとUnity Editor上でRemove Mesh In Boxが作成されていたケースが考えられます。
Unity Editor上で作成されていた場合にInitializeを実行しようとすると、前者2つのケースでInitializeを二重に実行してしまう懸念があります。
また、ここで提示しているユースケースでは、対象GameObjectは配布アセットを使用するユーザーのアバターのものであるため、改変の一環としてUnity Editor上でRemove Mesh In Boxコンポーネントが既にアタッチされている可能性が否定できません。

関連ドキュメント: https://vpm.anatawa12.com/avatar-optimizer/ja/docs/developers/component-api/#getting-started

**Comment by anatawa12** [comment]
すでに追加されているコンポーネントに対する操作は対応できないと考えています。

例えば #1035 が次のバージョンで追加する予定がありますが、これが有効なコンポーネントをされた場合、Boxを追加すると削除する対象ではなく削除されない対象が追加されることになる可能性があります(仕様の詳細は未定です)。
そして、v1.8.0を知らないツールは、この反転機能がオンになっていることを知りえないので、今まで通りにBoxを追加することにより削除する対象が増えることを期待しますが、逆に削除する対象が減ってしまうということになります。

このような非互換性に対する適切な対処法がないと考えているため、すでに追加されているコンポーネントに対する操作は非対応としています。

**Comment by Tatamo** [comment]
Remove Mesh in Boxが対象のSkinned Mesh Rendererに対して直接アタッチする必要があり、かつ単一のコンポーネントしか追加できないことから、アバターの素体メッシュに付与されたRemove Mesh in Boxに対して複数のアプローチが重複することは避けられないように思います。
(#1035 に関しても、一部のメッシュを残して、さらにその一部を削除したいという需要が並存しそうなので、コンポーネントではなくBoxに対して設定できたほうがいいかなと思います)

または、Remove Mesh in Boxを同時に複数付与可能にするというのは技術的に困難なのでしょうか？

**Comment by anatawa12** [comment]
> 複数のアプローチが重複することは避けられないように思います。

はい。そのため対応外にしている状態です。

> Remove Mesh in Boxを同時に複数付与可能にするというのは技術的に困難なのでしょうか？

こちらに関してはあまり問題はないので、`[DisallowMultipleComponent]`を外すことはできると思います。

**Comment by Tatamo** [comment]
存在チェックを行わずに常に新しいコンポーネントを生成してよいのであれば、このIssueの問題も解消されるのでとても嬉しいです。

> すでに追加されているコンポーネントに対する操作は非対応としています。

https://vpm.anatawa12.com/avatar-optimizer/ja/docs/developers/component-api/ では追加と設定変更が可能と記載されており、
「コンポーネントの設定を変更する場合は、将来のバージョンで追加される機能との互換性を確保するためにvoid Initialize(int version)メソッドを呼び出す必要があります。」という一文から自身が追加したものに対する設定変更だけが可能ということを読み取るのが難しかったので、ドキュメントにその旨が明記されているとよいなと思いました。

**Comment by anatawa12** [comment]
> 存在チェックを行わずに常に新しいコンポーネントを生成してよいのであれば、このIssueの問題も解消されるのでとても嬉しいです。

それではこのissueはcloseとして別 issue として制限を緩めるものを作ります。

> 「コンポーネントの設定を変更する場合は、将来のバージョンで追加される機能との互換性を確保するためにvoid Initialize(int version)メソッドを呼び出す必要があります。」という一文から自身が追加したものに対する設定変更だけが可能ということを読み取るのが難しかったので、ドキュメントにその旨が明記されているとよいなと思いました。

わかりました。追記します。
