### ISSUE TITLE
Duplicate language options in the Editor Language selector

### ISSUE THREAD

**Issue by gizmo-ds** [anatawa12/AvatarOptimizer#1209]
![image](https://github.com/user-attachments/assets/64215d57-95b3-4a02-8531-2016a8dd0227)

I noticed that the Editor Language selector includes both '中文 (简体)' and '中文 (中国)' as options for Simplified Chinese, but the content displayed for these two options is identical. Since there is already a '中文 (繁體)' option for Traditional Chinese, I suggest removing the '中文 (中国)' option and keeping only '中文 (简体)' to maintain consistency with the '中文 (繁體)' format.

**Comment by anatawa12** [comment]
The locale selector is from NDMF and shared with NDMF Plugins.
I think this is because another NDMF Plugin use zh-hans and AAO is using zh-cn.

we may change to zh-hans instead of zh-cn for this difference
