### ISSUE TITLE
Merge PhysBoneではNetworkIDを指定することが出来ない

### ISSUE THREAD

**Issue by Sayamame-beans** [anatawa12/AvatarOptimizer#1258]
タイトル通りです。これにより、同期面で問題が発生する可能性があります。

解決策の1つとしては、統合後のPBとなるPhysBoneを1つ関連付けてattachする手があります。(副産物として統合後のPBをアニメーションしやすくなります)
もう1つは、MergePB側にNetworkIDの設定項目を用意することですが、NetworkID Utility等との都合で色々ややこしくなりそうです…?

**Comment by anatawa12** [comment]
そういえばそんなんありましたね......

NetworkID Utilityに関しては`VRC.SDKBase.INetworkID`の実装クラスがあると多分処理されるので、MergePhysBone自体に`VRC.SDKBase.INetworkID`を実装しちゃうことで解決する可能性ありそう。

------

誰か研究してくれると助かる

**Comment by anatawa12** [comment]
#1260 で設定できるようになった気がするのですが問題なさそうか確認してほしいです

**Comment by anatawa12** [comment]
VQTの互換性の方も確認しといたほうがいいかもねとなった

**Comment by Sayamame-beans** [comment]
-> https://kurotu.github.io/VRCQuestTools/ja/docs/references/components/network-id-assigner

**Comment by Sayamame-beans** [comment]
> ## Generating Phase
> ネットワークIDのないPhysBoneにネットワークIDを割り当てます。

だから厳しい可能性がありそう

**Comment by anatawa12** [comment]
https://github.com/kurotu/VRCQuestTools/blob/9e7977220b8ddd95db30fb1e808cada6fe29f7b3/Packages/com.github.kurotu.vrc-quest-tools/Editor/Utils/VRCSDKUtility.cs#L404

コンポーネント一覧の取得が同じ仕組みなので原則は大丈夫そう

**Comment by Sayamame-beans** [comment]
いい話
じゃあこれで大丈夫かも?

**Comment by Sayamame-beans** [comment]
一見問題なさそうなので問題ない気がします
PlayModeやアップロード後に意図したIDが割り当てられているかを確認する術が分からないのであれですが…(後者は実際にPC/Android間で動作確認するしかない?)

**Comment by anatawa12** [comment]
Play 状態でUtilityでみるか、Debug InspectorでDescriotorのなかを確認するかくらいかな

**Comment by Sayamame-beans** [comment]
> Debug InspectorでDescriotorのなかを

見落としたのか、どこか分からなかったのです

> Play 状態でUtilityでみる

たしかに…

**Comment by Sayamame-beans** [comment]
PlayModeだとUtility閉じちゃいますね

Inspector、場所分かりました
Playmode入る前に割り当てていても、入ったときに割り当て直されていそうですね。また、MAやAAOがHierarchyの位置を変更するので順番も(ビルド前とは)変わっていそう。
また、Playmodeを抜けると、ビルド前に割り当てていたNetworkIDは失われています。
(ワールドの方ではVRCSDK側がバグっているので、アバターももしかしたら…? 或いは、NDMFで複製したときに何かしらある…? 要検証です)

VQT Network ID Assignerを付けると、割り当て直し等によるID変更は発生しません。代わりに(Generatingでやってるので)余分にNetworkIDを割り当てた状態にはなっています。

**Comment by anatawa12** [comment]
> Playmode入る前に割り当てていても、入ったときに割り当て直されていそうですね。

VRCSDKのバグだったりしないかな

余分につくのはそう。想定内
