### ISSUE TITLE
Merge Skinned Meshが行われないレンダラーに対してはマテリアルスロットが結合されない…？

### ISSUE THREAD

**Issue by Tliks** [anatawa12/AvatarOptimizer#1284]
ルートにTrace and Optimizeをアタッチし、複数のマテリアルを持つSMRに対しTTT Atlas Textureでマテリアル結合を行った環境において、対象のSMRが(Auto) Merge Skinned Meshの対象外である場合に同一のマテリアルスロットが結合されていないように見えます。

以下の写真はFaceとFace_effectをTTTで結合した際のPlayModeに入る前後のインスペクターです。BodyはアニメーションによりAuto Merge Skinned Meshの対象外であり、Merge Skinned Meshもアタッチしていません。
![スクリーンショット 2024-10-20 172036](https://github.com/user-attachments/assets/209ab05c-05fe-4b67-85b2-9afacb5210de)
![image](https://github.com/user-attachments/assets/8b905006-919d-4127-afc3-f5884228611a)

Merge Skinned Meshにより結合後のRendererとなった場合には重複していません。認識に間違いがあったらすみませんが、(Auto) Merge Skinned Meshを介せずともそれ以外のTrace and Optimize内の処理で重複したマテリアルスロットは結合される動作を想定していました。

**Comment by anatawa12** [comment]
仕様です

**Comment by Tliks** [comment]
可能であれば結合されない理由を聞いても良いですか…?

**Comment by anatawa12** [comment]
理由はあまりないですが、マテリアルスロットの自動結合は Merge Skinned Mesh のおまけという実装をしてるので、現状はしようってだけで、マージするようにするのに問題はありません

**Comment by Tliks** [comment]
理解しました、ありがとうございます。
