### ISSUE TITLE
MA、VRCFuryと併用中プレハブファイルが失われてインポートから進まなくなる

### ISSUE THREAD

**Issue by ni1chigo2115** [anatawa12/AvatarOptimizer#132]
VRCFuryとmodular avatarの二つと併用しているとき、フリーズブレンドシェイプが依存関係に失敗して、スキンドメッシュレンダラーを削除できなくなり、結果的にプレハブファイルが失われてインポートから進まなくなる
MAはベータ版、VRCSDKとVRCFuryは最新版です
厄介なことに、MAやVRCFury、それどころかAvatarOptimizerのコンポネートを不使用でも発生します
TEMPフォルダはCではなくEドライブを使用しています
![missing2](https://user-images.githubusercontent.com/23652237/236187072-31623fe6-e1c2-469b-a31d-8b0db8cc7ba2.jpg)

**Comment by anatawa12** [comment]
再現しました。　#133 でCan't remove SkinnedMeshRendererのエラーを消しても発生するので本当に謎ですね...
調査します。

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/22656849/236402624-f0565ff1-ad24-469f-b872-15bc1283f169.png">
