### ISSUE TITLE
キメラアバターのBodyをAuto Merge Skinned Meshから除外する

### ISSUE THREAD

**Issue by nomlasvrc** [anatawa12/AvatarOptimizer#1364]
Bodyがアバタールート直下にない場合（例えば`Kikyo/Manuka/Body`などの場合）Bodyと認識されずメッシュがマージされてしまうので、下の階層まで検索するか、LipSyncで指定されたFace Meshを除外して、オートマージされないようにしてください。

**Comment by anatawa12** [comment]
Avatar Descriptor の設定を更新することでAutoMergeSkinnedMeshの対象でもLipSyncが動作するように設計していますが、正しく動いてない感じでしょうか

**Comment by anatawa12** [comment]
補足説明をしますと、Trace and Optimize で Body がマージされない事があるのは、MMDワールドとの互換性を破壊しないための機能によるものになっており顔メッシュであるからマージしないような仕組みは現在ありません。(必要がないと認識しています。)
実際 Body がアバターのルートにある場合でも MMD ワールドとの互換性のオプションを無効化するとマージされるようになっています。

もし顔のメッシュであるからマージされては困る事例があれば教えて下さい。

**Comment by nomlasvrc** [comment]
> Avatar Descriptor の設定を更新することでAutoMergeSkinnedMeshの対象でもLipSyncが動作するように設計していますが、正しく動いてない感じでしょうか

LipSyncは正しく動作しました。

> もし顔のメッシュであるからマージされては困る事例があれば教えて下さい。

ブレンドシェイプ数が多いメッシュはマージすると逆に負荷が大きくなる…というのを以前見たので気になったのですが、現在は違うのでしょうか。

**Comment by anatawa12** [comment]
> ブレンドシェイプ数が多いメッシュはマージすると逆に負荷が大きくなる…というのを以前見たので気になったのですが、現在は違うのでしょうか。

AAO v1.8 で Unity 更新に伴ってその表記は削除されました。

https://vpm.anatawa12.com/avatar-optimizer/ja/docs/reference/merge-skinned-mesh/

> 以前のAvatar Optimizerは顔のメッシュを他のメッシュと統合することを推奨していませんでした。 これは、Unity 2019でBlendShapeの多いメッシュを統合するとメッシュの負荷が大幅に増加してしまうためです。
Unity 2022ではBlendShapeの負荷が改善されているため、その記述は取り下げられました。

**Comment by nomlasvrc** [comment]
分かりました。Bodyめっしゅマージありがとうございます。
