### ISSUE TITLE
[merge skindmesh]同じマテリアルを使ったskinedmeshをマージするとき、頂点がぴったり重なる場所があれば頂点ごと結合するオプション

### ISSUE THREAD

**Issue by ni1chigo2115** [anatawa12/AvatarOptimizer#138]
頭と身体を一つのメッシュにまとめるなどをしたときに、特定のシェーダーだとライティング処理で継ぎ目が目立ってしまうことがあります
結合してからFBXに出力して、Blenderで修正するという手もなくはないですが、いかんせん破壊的改変になってしまいます。
もしもメッシュをまとめるときにぴったりの重なる頂点があったときに、結合してくれるオプションがあるとうれしいです

**Comment by ni1chigo2115** [comment]
位置、UVは確実に同じでいいと思います（そうなるとタンジェントも）
法線が厳しいですね、片方だけシャープ化してたりすると法線が違ったりするので・・・

**Comment by anatawa12** [comment]
> 特定のシェーダーだとライティング処理で継ぎ目が目立ってしまうことがあります

確認したいのですが、マージ前とマージ後で見た目が変わるということでしょうか？

**Comment by ni1chigo2115** [comment]
うーむ
