### ISSUE TITLE
使われていないPhysBone Colliderを削除するcomponent

### ISSUE THREAD

**Issue by Narazaka** [anatawa12/AvatarOptimizer#158]
MAで同じ服を部分ごとに別prefab管理（ex.靴と靴下それぞれのみ以外をEditorOnlyにするなど）にしてから1アバターに結合した際にPhysBone Colliderが重複したりする

MAは同パスならPBは結合（というか無視？）してくれる模様だが、PB Colliderについては単にぶら下げる管理になるっぽいのでPB Colliderだけ残る

**Comment by anatawa12** [comment]
#291 #401 でコライダーが残るのは解決すると思います

設定重複は #304 のあと自動化も検討します
