### ISSUE TITLE
PrefabSafeSetにて、リストに全て表示されないことがある

### ISSUE THREAD

**Issue by hitsub** [anatawa12/AvatarOptimizer#228]
## 概要

MergeSkinnedMeshにおけるSkinnedMeshRenderersの一覧として表示されるものと、実際の中身が異なるケースがあります。  
動作に問題は無く、表示のみのようです。

また、MergePhysBoneにおけるPhysBone一覧でも同様の問題が発生します。

Inspector (Normal)
![image](https://github.com/anatawa12/AvatarOptimizer/assets/5540614/48c6fb81-01a2-4d5d-bfe2-0b298a190bc6)

Inspector (Debug)
![image](https://github.com/anatawa12/AvatarOptimizer/assets/5540614/85dbd255-c27a-4b6a-bf2e-3aa941c13e14)

## 再現手順

1. ２つのメッシュ(以下メッシュA、B)を含み、AのみMergedSkinnedMeshへ登録した状態のPrefab1を作成 
![image](https://github.com/anatawa12/AvatarOptimizer/assets/5540614/32d8aae0-64d6-4847-8553-391e87e3e4b0)

2. Prefab1のVariantであるPrefab2を作成し、メッシュBをMergedSkinnedMeshを登録する
![image](https://github.com/anatawa12/AvatarOptimizer/assets/5540614/e3e63c0f-0e64-40f3-a638-238fb6c4a3b5)

3. Prefab2のVariantであるPrefab3を作成する
4. Prefab3をSceneあるいはPrefabModeで見ると、メッシュAのみが登録されているように見える 
![image](https://github.com/anatawa12/AvatarOptimizer/assets/5540614/673f2a7c-d3d3-47ae-a054-701e0931fcd4)

## 確認したバージョン

- 1.0.0-beta3

**Comment by anatawa12** [comment]
#52 の修正にミスが有りました。
おそらくPrefab3に要素を追加してinspectorを開き直すと治ります

**Comment by hitsub** [comment]
修正ありがとうございます🙇
