### ISSUE TITLE
「使われない」ものをEditorOnly扱いしたい

### ISSUE THREAD

**Issue by Narazaka** [anatawa12/AvatarOptimizer#230]
ランタイムに常にinactive/disable等で実効的に使われないコンポーネントやボーン等を自動計算して実質EditorOnly扱いにしたい

アバター改変時には

- Unpackして削除する
- GameObjectのinactiveで表示を消す

運用が一般的で、EditorOnlyの調整までしなさそうなので。

アバター直下にそれ用のコンポーネントを付けると全体自動でやるイメージ。

**Comment by anatawa12** [comment]
常にinactive/disableの削除は #401 で実装したのでたぶんこれのゴールは達成しています。
