### ISSUE TITLE
ランタイムにMeshの表示・非表示にあわせてPhysBoneコンポーネントを自動で有効化・無効化したい

### ISSUE THREAD

**Issue by Narazaka** [anatawa12/AvatarOptimizer#231]
着せ替えツール等でMeshの表示状態を切り替えた際に、表示に影響を及ぼさなくなったPBが動作したままになる問題があるので、これを自動的に連動できたら良さそうです。

- バグっぽい挙動無く行うには実質的にメニューとステートマシンの解析が必要そうで**とても**難しそう
  - 着せ替えツールの責任範囲である気もする
- アバター直下にそれ用のコンポーネントを付けると全体自動でやるイメージ

**Comment by Narazaka** [comment]
あるいはPBと同じGameObjectにつけるとか、対象のPBを指定するとかでも良いのかもしれない（パラメーター連携するやつとかを消して良いのか自動判定出来るのか微妙だと思ったため）

**Comment by anatawa12** [comment]
#640
