### ISSUE TITLE
modular avatarのReplaceObjectへの対応

### ISSUE THREAD

**Issue by ni1chigo2115** [anatawa12/AvatarOptimizer#293]
modular avatarにreplace objectが追加されました。
この機能はアニメーションの参照先を維持したまま統合して、様々なものを書き換えれる便利ですが、
MergedSkindMeshとは相性が悪くて、うまくMergeしながら統合先に書き換える、というのができないようです。
真新しい機能なので、専用の対応が必要に感じます。

**Comment by anatawa12** [comment]
具体的に対応が必要な作りを教えて下さい。

**Comment by anatawa12** [comment]
具体的にうまく動かない構造を教えて下さい。

**Comment by ni1chigo2115** [comment]
![replace object_MA](https://github.com/anatawa12/AvatarOptimizer/assets/23652237/9175c549-0a8a-4883-95b3-89a6322aa433)
こんな感じです

**Comment by anatawa12** [comment]
Replace ObjectあとはMergeSkinnedMeshが自己参照するようになる感じですかね...?

MAとAAOは完全に独立して動き、Merge Animatorとかの問題が発生するため、AAOがあとに適用されるようになってます。

そのため自己参照になってそうに見えます。自己参照はうまく動くようにできてないのでエラーにならないのがバグですね。
