### ISSUE TITLE
Make Childrenがmodular avatarのPhysBoneBlockerを参照しない。

### ISSUE THREAD

**Issue by ni1chigo2115** [anatawa12/AvatarOptimizer#294]
MakeChildren機能を使うと、入れ子構造でBreastを統合できて、プレハブを維持したまま複雑なBreastの挙動が可能になって便利です。
しかし、どうもPhysBoneBlockerにはうまく反応しなくて、結局直接参照するようにしてしまいました。
しかし、PhysBoneBlockerに対応してくれた方がありがたいので、参照できるようにできないでしょうか？

**Comment by anatawa12** [comment]
Make ChildrenにMAの前に実行するオプションはやしますね。

**Comment by ni1chigo2115** [comment]
試しましたがうーむ、予想はしてましたが早期に胸構造を入れ替えたためにアーマチュア構造が変化してmerge armtureがうまくいかなかったようです。
・・・早期にMakeChildrenを実行するのはいい機能ですが、AAO版PhysBoneBlockerを新たに併設して、自分でコンポネートを埋め込んでもいいし、他の非破壊ツールのPhysBoneBlockerを検知したら自動でAAO版PBBを埋め込む、という形にした方がいいかも

**Comment by anatawa12** [comment]
Make Children自体がAAOの中にあるべきか怪しいと思っててbd_さんのframeworkにのりしだい別途make children等を持ったツールを考えてるのでPhysBoneBlockerはAAOで流行らないと思います

**Comment by ni1chigo2115** [comment]
その場合は新ツールに乗り換えたら、前のスクリプトコンポネートがそのまま使いまわせる挙動だと嬉しいです
