### ISSUE TITLE
MergePhysBoneコライダー

### ISSUE THREAD

**Issue by ni1chigo2115** [anatawa12/AvatarOptimizer#304]
題名通りです、複数あるが値が一緒のコライダーの参照を一つに統一するのが目的といった感じです。

例えば地面コライダーなどは、すべて0位置の平面なので、一つに統合してコライダー総数を減らした方がいい気がします。
特殊・特別な事例としてmodular marshmallowなどの内部的にプレハブの中身を見ることができない非破壊ツールを検知して、地面コライダーを検知した場合に統合するかどうかのオプションだけはちょっとほしいかな・・・。

基本的にはMergePBと同じく、同じ部位同じ数値が使われていることが条件です。

**Comment by anatawa12** [comment]
地面コライダーやグローバル固定Constraintのような色々使われる想定のものはMA側にほしいって言いたいかなぁ

関係なくMerge PB Colliderは需要ありそうですね
