### ISSUE TITLE
更新通知

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/AvatarOptimizer#316]

**Comment by Sayamame-beans** [comment]
lilToonの場合では、masterブランチにある[version.json](https://github.com/lilxyzw/lilToon/blob/master/version.json)を見ているみたいでした。

https://github.com/lilxyzw/lilToon/blob/2ef370dc444172787c075ec3a822438c2bee26cb/Assets/lilToon/Editor/lilInspector.cs#L3515-L3520 
https://github.com/lilxyzw/lilToon/blob/2ef370dc444172787c075ec3a822438c2bee26cb/Assets/lilToon/Editor/lilInspector.cs#L3532-L3551 
https://github.com/lilxyzw/lilToon/blob/2ef370dc444172787c075ec3a822438c2bee26cb/Assets/lilToon/Editor/lilStartup.cs#L123-L128 
https://github.com/lilxyzw/lilToon/blob/2ef370dc444172787c075ec3a822438c2bee26cb/Assets/lilToon/Editor/lilStartup.cs#L171-L187 
https://github.com/lilxyzw/lilToon/blob/2ef370dc444172787c075ec3a822438c2bee26cb/Assets/lilToon/Editor/lilConstants.cs#L14

**Comment by anatawa12** [comment]
方法論的にはそんなかんじになるのはそう。

AAOのばあいは公式サイトにversion.txtはやそうかなとも思ってる。

問題は通知を表示させる場所がない

**Comment by Sayamame-beans** [comment]
確かに…画面上に通知を出す方法が用いられている拡張もありますが、煩わしく感じそうですし…

**Comment by anatawa12** [comment]
ビルド時に更新がある場合info / warnレベルで出すのが丸い気がしてきた。 @Sayamame-beans どう思う？

**Comment by Sayamame-beans** [comment]
それは良いかもしれないですね
