### ISSUE TITLE
最適化からGameObject単位で除外する

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/AvatarOptimizer#374]
バグのworkaround用?
でもあんま提供したくない気持ちがある

**Comment by anatawa12** [comment]
用途募集中

**Comment by Sayamame-beans** [comment]
Trace And Optimizeからの除外であれば、消されたくないBlendShapeがある場合とか…?(MMDワールドと同様の技術が他で使われる可能性?)
#334 で手動設定での無効化は出来なくなっていそうですし

**Comment by anatawa12** [comment]
方法論的にはそんなかんじになる。

AAOのばあいは公式サイトにversion.txtはやそうかなとも思ってる。

**Comment by anatawa12** [comment]
消されたくないBlendShape、かのうならT&O側での対応とかにしたさはあるのよね...
