### ISSUE TITLE
海外からのエラー報告(freeze blendshape)

### ISSUE THREAD

**Issue by ni1chigo2115** [anatawa12/AvatarOptimizer#378]
FreezeBlendShapeを使うパッケージを海外向けに配布したところ、ユーザーの一人がエラーを起こしたようです。
ログを添付します。

もし必要であれば、該当アセットと組み合わせ、プレハブなどを用意します。
あともしも報告する場合、該当パッケージはNSFW系のものです、気を付けて

[Error.txt](https://github.com/anatawa12/AvatarOptimizer/files/12435151/Error.txt)

**Comment by anatawa12** [comment]
該当assetの提供をお願いしたいです

**Comment by ni1chigo2115** [comment]
> 該当assetの提供をお願いしたいです
https://skuny.gumroad.com/l/3PACC
要パッケージ
・VRCFury
・iltoon
・anatawa avatar optimizer
（poiyomiとかDPSのマテリアルは無視してください）
TVF - Penetrator PACC from gumroad 
https://skuny.gumroad.com/l/3PACC
あとうちが作ったプレハブを封入したパッケージです
[TVF-penetratrorpacc_VRCFHP_SPSPrehab.ZIP](https://github.com/anatawa12/AvatarOptimizer/files/12436425/TVF-penetratrorpacc_VRCFHP_SPSPrehab.ZIP)
うちが作ったプレハブを使用すると、AAOでエラーが出るとのことです。

**Comment by anatawa12** [comment]
ありがとうございます。まず元のアセットがRead Write Mesh offの状態で配布されているようなのでR/W Mesh onにしているかを元の報告者に確認していただきたいです

**Comment by ni1chigo2115** [comment]
本人は不本意そうでしたが、アップロード時にVRCSDK側からメッシュ設定の警告に従ってオンにしたら、VRCFury側からのWarningも含めたエラーがでなくなったそうです。
read&writeがオフのモデルに対して、適切に処理できないことが原因かもしれません。

**Comment by anatawa12** [comment]
R/W offだとどうしてもメッシュの処理ができないので仕様になりますね。エラーが出てないのが問題になると思うのでエラー出すようにします

#385
