### ISSUE TITLE
Unknown Component Typeの日本語化

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/AvatarOptimizer#406]
https://github.com/anatawa12/AvatarOptimizer/blob/fd75ab0db3ae386ba0d64daf5a09a343334e05fc/Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs#L111

**Comment by anatawa12** [comment]
@Sayamame-beans 日本語表現なにかいいと思いついたら教えていただきたいです。

**Comment by Sayamame-beans** [comment]
`未知のコンポーネント \"{0}\" を検出しました! これにより最適化の性能が低下する可能性があります。もしよろしければ、これをAvatarOptimizerに報告してください。`
みたいな感じでしょうか?
ちなみにこれってWarningじゃないと駄目なのでしょうか? (Infoぐらいでも良いのかなと思ったりしたのですが、最適化という観点で見るとWarn…ですかね?)

**Comment by anatawa12** [comment]
Warnなの、この未検知によって場合によってはアバターが壊れるからですね。そのコンポーネントが想定外の動きすると壊れるので。

**Comment by anatawa12** [comment]
May Break Avatarってかき忘れてた

**Comment by Sayamame-beans** [comment]
あー、なるほど
