### ISSUE TITLE
ja.po, en.po内の改行の有無など

### ISSUE THREAD

**Issue by Sayamame-beans** [anatawa12/AvatarOptimizer#455]
https://github.com/anatawa12/AvatarOptimizer/blob/29320967eff7197360f7b0163dec995b7dc0d475/Localization/ja.po#L332
https://github.com/anatawa12/AvatarOptimizer/blob/29320967eff7197360f7b0163dec995b7dc0d475/Localization/en.po#L396
ここに改行を付けていないのは意図的でしょうか?
また、
https://github.com/anatawa12/AvatarOptimizer/blob/29320967eff7197360f7b0163dec995b7dc0d475/Localization/ja.po#L138
https://github.com/anatawa12/AvatarOptimizer/blob/29320967eff7197360f7b0163dec995b7dc0d475/Localization/en.po#L135
の改行が2つであるのも意図的でしょうか?

**Comment by anatawa12** [comment]
前者、自動改行があるのでどっちでもいいと認識してます。

後者、空行を入れる意図がある。
