### ISSUE TITLE
高度なEditModeプレビュー

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/AvatarOptimizer#478]
とくにRemoveMeshByBlendShapeやRemoveMeshWithBoxでやりたい。

#66 の前にりたい

ReinaS-64892/TexTransTool#143 で覚えたプレビューをつかって実装できたらなぁと思った。

**Comment by Sayamame-beans** [comment]
これ結構良いと思います。
特に、現状のRemoveMeshByBlendShapeのプレビュー機能は実際に値を変更することで実現しているので、元が0,100以外の値だった場合に(間違って押したりしてしまうケースも含め)少し困りそうだなと思うので…
(Undoすれば良いという話ではあるかもしれませんが)
