### ISSUE TITLE
"或いは"と書いてあるが、実際には固定と除去が同時に発生する

### ISSUE THREAD

**Issue by Sayamame-beans** [anatawa12/AvatarOptimizer#480]
https://github.com/anatawa12/AvatarOptimizer/blob/08ec0b30cfc010c32d0b71330b2d3100ae8d3046/.docs/content/docs/reference/freeze-blendshape/index.ja.md?plain=1#L8
` ブレンドシェイプをメッシュに固定し、除去することが出来ます。 `とかそんな感じで良さそうな感じがします。
ただ、そもそも"固定"した時点で"除去"が達成されている気もするので、除去とは言わずに固定だけでも良かったりしないでしょうか?)

**Comment by anatawa12** [comment]
あるいわ、言い換えのつもりでした
