### ISSUE TITLE
極端に小さいスケールを持つオブジェクトの親子関係圧縮時に意図しない回転成分が付加される

### ISSUE THREAD

**Issue by logicmachine** [anatawa12/AvatarOptimizer#497]
おそらく #491 と似た事象ですが 1.5.0-rc4 で発生したため再度起票します。

以下のような親子関係および Transform を持つオブジェクト群があり `A->B` 間の親子関係を圧縮できるようにします。

```
+ A
    + B: scale=(1.401298e-45, 1.401298e-45, 1.401298e-45)
```

この時 Trace and Optimize を適用すると以下のように変形されることが期待されます。

```
+ A$B$0: scale=(1.401298e-45, 1.401298e-45, 1.401298e-45)
```

しかし、実際には以下のように `A$B$0` の Transform が期待と異なるものになってしまいます。

```
+ A$B$0: rotation=(-33.913, -38.019, -38.019), scale=(0, 0, 0)
```

## 環境情報
- AvatarOptimizer v1.5.0-rc4

**Comment by anatawa12** [comment]
再現しました。
Unityの数学APIが当てにならないようなので独自に実装します
