### ISSUE TITLE
1.5.0.-rc9Issue MO-BlendshapeSyncコンポネートを無視する

### ISSUE THREAD

**Issue by ni1chigo2115** [anatawa12/AvatarOptimizer#521]
MO-BlendshapeSyncコンポネートを載せて、一つ以上のBlendShapeを親元とリンクした状態のSkinedMeshをMergeSkinedMeshを対象にしても、BlendShapeSyncの対象からは外れてしまうようです。
逆に、MergeSkinedMeshにBlendShapeSyncコンポネートをつけて設定しても、無視されてしまうようです。
現状ではBlendshapeSyncを前提としたメッシュは、統合が難しいという感じになっています。

**Comment by anatawa12** [comment]
MOとかいてありますがModularAvatarのことだと推測して書きます。

そもそもAvatarOptimizerを動かさない状態にしてもBlendShape SyncのアニメーションのSync機能が動いていないように見えます。(bdunderscore/modular-avatar/issues/461)そのためAAOの問題ではないと思われます

**Comment by anatawa12** [comment]
修正されたはずな状態になってから一週間経ったのでCloseします
