### ISSUE TITLE
一部の画像が適切でない

### ISSUE THREAD

**Issue by Sayamame-beans** [anatawa12/AvatarOptimizer#528]
例えば、
https://github.com/anatawa12/AvatarOptimizer/blob/db3250c2a464386106a1f0ae2b51230ff51eebc5/.docs/content/docs/tutorial/basic-usage/add-merge-skinned-mesh.png 
~~https://github.com/anatawa12/AvatarOptimizer/blob/db3250c2a464386106a1f0ae2b51230ff51eebc5/.docs/content/docs/reference/make-children/component.png~~
https://github.com/anatawa12/AvatarOptimizer/blob/db3250c2a464386106a1f0ae2b51230ff51eebc5/.docs/content/docs/reference/merge-bone/component.png
などを観測しています。
少なくとも前者はチュートリアル中に登場するため、最新のものであることが望ましいと考えます。

**Comment by anatawa12** [comment]
https://misskey.niri.la/notes/9ki2pjez0s

> そういえばmerge boneのreferenceだけ日本語pngになってる

**Comment by Sayamame-beans** [comment]
ちょっと修正しました
