### ISSUE TITLE
much more refine of docs

### ISSUE THREAD

**Issue by Sayamame-beans** [anatawa12/AvatarOptimizer#573]
https://misskey.niri.la/notes/9kqt6v2b0h
https://misskey.niri.la/notes/9kqt110ii9
https://misskey.niri.la/notes/9kqt7edkjm

**Comment by Sayamame-beans** [comment]
このドキュメントは初心者向けのものではないと私は認識しています([理由の一端](https://github.com/anatawa12/AvatarOptimizer/discussions/345#discussioncomment-6977523))ので、Unityの諸々に慣れていない人が分かりやすい表現にはなっていないはずです。
必要であればそれに沿えるよう出来るだけ努力いたしますが、 @anatawa12 さんはどのようにされたいでしょうか?

**Comment by anatawa12** [comment]
レファレンスマニュアル部分はある程度わかっててドキュメントが読める人(単語は調べる人)を想定したい。メンテコスト的にも。

トップページやbasic usageチュートリアルはアバタ改変初心者くらいまで下げたほうが良さそうって思ってます

**Comment by Sayamame-beans** [comment]
なるほどです。
