### ISSUE TITLE
humanoidボーンを使いながらそれにウエイトが乗っていないアバターでTrace And Optimizeがエラー

### ISSUE THREAD

**Issue by Narazaka** [anatawa12/AvatarOptimizer#583]
下記のような実質GenericアバターであるがQuestフォールバック対応等の都合（QuestフォールバックはGenericアバターだと申請できなかった気がする）でHumanoidボーンを含んでいる場合
![image](https://github.com/anatawa12/AvatarOptimizer/assets/1712548/85d99bfd-e748-4d89-bb00-a11517e14127)
Trace And Optimizeをデフォルト設定でそのままビルドするとhumanoidボーンが足りない旨のエラーが出てきて
![image](https://github.com/anatawa12/AvatarOptimizer/assets/1712548/a2f78308-56c4-4b2d-8c5c-d963e025d737)
じっさいmanual bakeするとheadのボーンが吹っ飛んでいる
![image](https://github.com/anatawa12/AvatarOptimizer/assets/1712548/a9518fee-edd2-4191-ab69-cbcab3e1c3d9)

Remove unused Objects Automaticallyをオフにすると動作する。
- Humanoidボーンは保持するみたいな風にした方が良い？
- Humanoidボーンにウエイトが乗ってないときに警告？
- エッジケースだから対応しないという方針もありそう

**Comment by anatawa12** [comment]
Humanoidのボーンは残す方針にしてたので普通に実装ミスです
