### ISSUE TITLE
feat: Non-VRChat Avatars support

### ISSUE THREAD

**Issue by kaikoga** [anatawa12/AvatarOptimizer#607]
### Discussed in https://github.com/anatawa12/AvatarOptimizer/discussions/522

Wrap VRCSDK dependencies of AvatarOptimizer in compile flags to support non-VRChat avatars.

## Required Tasks

- [x] Add `#if UNITY_2020_2_OR_NEWER`
- [x] Add Version Define `AAO_VRCSDK3_AVATARS` against "com.vrchat.avatars"
- [x] `#if AAO_VRCSDK3_AVATARS` VRChat specific AAO components
- [x] `#if AAO_VRCSDK3_AVATARS` VRChat specific AAO passes
- [x] Use ndmf 1.2.0 API to reduce VRCAvatarDescriptor usage (if any)
- [x] `#if AAO_VRCSDK3_AVATARS` VRCSDK component references within generic AAO components
- [x] Update code generators

## Not right now (create another issue)

- UniVRM support: VRM0 / VRM1
  - Add Version Define `AAO_VRM1` against "com.vrmc.vrm" and/or `AAO_UNIVRM` against "com.vrmc.univrm"
  - Add VRM related implementations to AAO, compile flags guarded
    - Add UniVRM component references to generic AAO components
      - Ideas here
    - Implement UniVRM specific AAO components and passes , if AAO is a better place
      - Ideas here
    - Other possible VRM specific optimization 
      - Ideas here
- Other non-VRChat avatar supports (by someone)

**Comment by kaikoga** [comment]
Done?

**Comment by anatawa12** [comment]
> Done?

Yes.

Thank you a lot for your hard work.
