### ISSUE TITLE
アニメーションで初期値から変化しないBlendShapeが除去される

### ISSUE THREAD

**Issue by kurotu** [anatawa12/AvatarOptimizer#621]
## 再現手順

テスト用アバター: 桔梗 Ver.1.04 Kikyo_PB.prefab

1. BlendShapeを操作するアニメーションを作成する (1フレーム目の値から変化しないものにする)
   <img width="688" alt="image" src="https://github.com/anatawa12/AvatarOptimizer/assets/74851548/b9a004fe-a555-46f5-8d7b-071f92c021f0">
2. FXレイヤーに新規レイヤーを追加し、1のアニメーションを再生するのみとする。
    <img width="495" alt="image" src="https://github.com/anatawa12/AvatarOptimizer/assets/74851548/0937e75f-239b-4292-91b2-502d55866d47">
3. Gesture Manager等で動作を確認する。
4. Trace And Optimizeを設定する (すべてデフォルト)。
5. 再び動作確認をすると、1のアニメーションで変化すべきBlendShapeが除去され、メッシュにも反映されていない。

1のアニメーションだけでAnimator Controllerを新しく作りFXレイヤーに設定した場合には問題は発生せず、細かな再現条件はわかりませんでした。

## 期待する動作
Animator Controllerが操作するBlendShapeを除去しない。
または、アニメーションの初期値でBlendShapeを反映した状態でメッシュを生成する。

実際のユースケースとして、デフォルト表情を変えるための1フレームだけのアニメーションをMA Merge AnimatorでFXレイヤーに追加する使い方をしており、この現象により表情が意図しないものとなっています。
シーン上のPrefabに対して同じBlendShapeをオーバーライドで変更することで、とりあえずは問題を回避できています。

## 環境情報
- Avatar Optimizer 1.5.6

**Comment by anatawa12** [comment]
元々変更後のweightでfreezeする使用でしたがFreezeBlendShapeが見るところが変わってそれとは別のところのweightにのみ変更してました。修正します

**Comment by anatawa12** [comment]
[v1.5.7-beta.1](https://github.com/anatawa12/AvatarOptimizer/releases/tag/v1.5.7-beta.1) で修正しました。確認お願いします。

**Comment by kurotu** [comment]
問題が修正されたことを確認しました。対応ありがとうございます。
