### ISSUE TITLE
may break your Avatar.警告でスペース抜けてる

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/AvatarOptimizer#631]
今更気付いたんですけど、この警告文`may break your Avatar.If your avatar`ってなってて空白が無いですね…?

_Originally posted by @Sayamame-beans in https://github.com/anatawa12/AvatarOptimizer/pull/623#discussion_r1366429226_

**Comment by anatawa12** [comment]
そもそもこのwarnツール作者に連絡してくれってのも追加したい

**Comment by Sayamame-beans** [comment]
端折って直しますが、#469 と同様に画像が古くなりますね(現時点でも、エラーの表示方法が変わっているので古くなっていそう)

**Comment by Sayamame-beans** [comment]
よく考えたらエラーの表示方法変えた時に直ってますね(別の場所に表示されている)
https://github.com/anatawa12/AvatarOptimizer/blob/32410dafc052b5b63d031cfe465d2d77d971489e/Localization/en.po#L493-L498
