### ISSUE TITLE
MergeSkinnedMesh: 最初からinactiveなGameObject/Rendererを無視するオプション

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/AvatarOptimizer#666]
inactiveなのが戻ってくるの正直わかりづらい気がするので

**Comment by anatawa12** [comment]
いれたら enabled by default for newly added, disabled by default for old for compatibility

**Comment by nekobako** [comment]
この挙動ほしかったのでとてもありがたいです！
試しに使用してみましたが、判定が逆になっていませんか？
mismatched な Renderer だけが統合されるようになっている気がします。

**Comment by nekobako** [comment]
修正助かります…！
もう一点、こちらは仕様か不具合か分からないのですが、enablement の判定は
`x.enabled && x.gameObject.activeSelf`
より
`x.enabled && x.gameObject.activeInHierarchy`
の方が適切だったりしませんでしょうか？
Scene 上の見た目での mismatch をスキップするなら後者かなと思いました。

(まとめて報告できればいいのですが、見つけ次第になってしまいすみません)

**Comment by anatawa12** [comment]
avatar rootまで遡ってactiveSelfしようとしてたのを雑にしようって書き換えたときに残ってるな...
avatar rootまでさかのぼるutilはやしてそっちにするか
