### ISSUE TITLE
Remove Empty Renderer ObjectがStatic Renderersは消しません

### ISSUE THREAD

**Issue by hisacat** [anatawa12/AvatarOptimizer#672]
Remove Empty Renderer Objectオプションを有効にすると、マージされたSkined Mesh Rendererの空のGameobjectは削除されますが、
マージされた Static Renderers (Mesh Filter/Mesh Renderer コンポーネント) の空の Gameobject は削除されません。

また、有用なアセットを開発していただきありがとうございます。

**Comment by anatawa12** [comment]
これは仕様です。

Merge Skinned MeshにおいてStatic Meshはボーンが一つのSkinned Meshとして処理され、そのボーンはMesh RendererがあったGameObjectに紐付けられるため、削除されません。

もしそのGameObjectを移動させていない場合にはTrace and Optimizeの`Remove unused Objects Automatically`を使用して削除してください。
