### ISSUE TITLE
Hips が Armature にマージされる (v1.6.0-beta.6)

### ISSUE THREAD

**Issue by nekobako** [anatawa12/AvatarOptimizer#713]
TraceAndOptimize で Hips が Armature にマージされてしまい、VRChat および Unity (Gesture Manager) で常に T ポーズになっていました。
No Configure Merge Bone をオンにすると発生しません。

v1.6.0-beta.6 で発生、v1.6.0-beta.5 では発生せずでした。

**Comment by anatawa12** [comment]
たぶんbeta.8で治ってます (beta.6/7では空Animator削除でアバタールートが消える不具合があったのでその影響があると思います)

**Comment by nekobako** [comment]
beta.8 でも発生していますね。。
遡ったら beta.6 からだったので beta.6 で発生と書きましたが、beta.8 で見つけたのでそっちを書くべきでした。

**Comment by nekobako** [comment]
`AnimatorInformation` の `if (!component.runtimeAnimatorController) return;` をコメントアウトすると直るのは確認していますが、それ以上は追っていません。
