### ISSUE TITLE
debug gui 2022で壊れてそう

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/AvatarOptimizer#799]

**Comment by tamakiii** [comment]
Screenshot

<details>

![image](https://github.com/anatawa12/AvatarOptimizer/assets/264325/c18f0d94-a7ed-4a7b-8cec-9a9d5bea696a)

</details>

下から2番目の `GC Debug/GC Debug Info (Script)` の `Entry Points` > `Component` 部分

確認した現象：
* `⦿` ボタンを左クリックしても何も起きない
* 右クリックするとプロパティパスのコピーなどのメニューが表示される
