### ISSUE TITLE
trace and optimizeで消えたPhysBoneによって揺らされていたBoneがMergeBoneされない

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/AvatarOptimizer#800]

**Comment by tamakiii** [comment]
Screenshot
※ `PhysBone.Leg.R` の `*end` GameObject に差分がある、という情報くらいしかない

<details>

![image](https://github.com/anatawa12/AvatarOptimizer/assets/264325/aff01f3c-12e8-4439-8e83-e6472bb85014)
![image](https://github.com/anatawa12/AvatarOptimizer/assets/264325/87c156cf-5794-4b9e-b8c2-a8239bfec65c)

</details>


確認した現象
* どのメッシュからも参照されていないだろう Bone が、Play, Build&Test, Test&Upload 後も消えずに残る
* `*end` GameObject は削除される

Note
* 無によって揺らされている判定を受けているかも？

暫定的な対処方法
* 消したい PhysBone から、`VRC Phys Bone (Script)` を `Remove Component` する
  * 該当 GameObject を disable するのでは消えずに残り続ける

**Comment by anatawa12** [comment]
方針案: Animator Parserのパース結果からGC Componentでけしたコンポーネントの影響を消せるようにする
