### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/AvatarOptimizer#814]
- MMDワールドで消えることがある場合にMerge SMRのRootBone設定されてるか確認しよう！

**Comment by Sayamame-beans** [comment]
MergeSMRとblendshape/animation系の話とかもFAQ枠ですね

こういう、問題が起きた時とかにぱっと見られるようなページは1つ欲しい感じありますね…
Trace and Optimizeで何か起きた場合は報告してねとかもそっちに入れたい
