### ISSUE TITLE
Stable API for components

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/AvatarOptimizer#832]
多分需要があるけどどのコンポーネントから手を付ければいいかがわからないのでほしいcomponentをユースケースとともに教えてください

**Comment by kb10uy** [comment]
* Merge Skinned Mesh
    - declavatar で切り替えアニメーションを生成する際、マージした状態でアニメーションを生成するようにしたい
    - 他のエディタ拡張などでも、切り替えパターン的にマージ可能なもの同士を自動でマージするような機能を実装する余地がうまれるはず
    - 極論ツールの都合のみで必要な GameObject/Component を手動で生成させたくない
* Remove Mesh by BlendShape / in Box
    - おおむね同上(外部エディタ拡張側のヒューリスティックなどでコンポーネントを付与できるメリットが大きそう)

**Comment by Sabu006** [comment]
* T&O
ユーザーにワンクリックでできる簡単な最適化機能として、T&Oのアバターへのアタッチを外部から行いたいため

**Comment by anatawa12** [comment]
T&Oについては原則デフォルト設定のみでも問題ないですかね

**Comment by Sabu006** [comment]
はい

**Comment by anatawa12** [comment]
現在要求があるものを #976 で仮に実装してみましたので、使用上で問題ないかを教えていただきたいです。

**Comment by kb10uy** [comment]
`RemoveMeshByBlendShape`, `RemoveMeshInBox`, `MergeSkinnedMesh` については問題なさそうです

**Comment by fu-sasa** [comment]
```T&O``` も問題ありません
