### ISSUE TITLE
Remove Mesh by UV Tile

### ISSUE THREAD

**Issue by Sayamame-beans** [anatawa12/AvatarOptimizer#838]
UV Tile Discardが普及した場合、需要が生じる

Originally: https://misskey.niri.la/notes/9ombvezb0d
> 今後UV Tile Discard標準セットアップのモデルが増えた場合、Remove Mesh By UV Tileが必要になる可能性が

**Comment by anatawa12** [comment]
これもMaterial Slot指定問題が発生しますね。ほんとどうしたらいいんだろ。

RMbUVTの場合はMergeSMR後を非対応にするとかでもいいのか

**Comment by anatawa12** [comment]
参考
- Tile Discardの実装 (Poiyomi): https://github.com/poiyomi/PoiyomiToonShader/blob/master/_PoiyomiShaders/Shaders/8.1/Toon/Poiyomi.shader#L10046-L10070
- liltoonの実装PR: lilxyzw/lilToon#158
- poiyomiのドキュメント: https://www.poiyomi.com/special-fx/uv-tile-discard

**Comment by anatawa12** [comment]
#1131 のあとにやる
