### ISSUE TITLE
略称を載せる？

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/AvatarOptimizer#842]
googleability的に。

`T&O` `MergeSMR` `MergePB`等

**Comment by Sayamame-beans** [comment]
コンポーネントごとのタイトル部分を弄って
`# Merge PhysBone (MergePB) {#merge-physbone}`
ってイメージです? ちょっと違う?

**Comment by anatawa12** [comment]
悪くはなさそう。

**Comment by Sayamame-beans** [comment]
問題無さそうであればこの方向で対応したいと考えています。
他にアイデアがあれば…? (Tips的に各ページのトップにあった方が良かったりしますか?)

**Comment by anatawa12** [comment]
各ページのタイトルはなくてもいいとは思う

> 問題無さそうであればこの方向で対応したいと考えています。

お願いします
