### ISSUE TITLE
Trace and Optimize時にConstraint系のコンポーネントIsActiveをアニメーションさせると不具合が発生する

### ISSUE THREAD

**Issue by piyoryyta** [anatawa12/AvatarOptimizer#856]
ワールドに固定できるオブジェクトを作成する際、Parent Contraint等の(通常はIs Enabledですが) ActiveをアニメーションさせるとConstraintにIs Enabledのアニメーションが付与され、正常に動作しなくなりました。

例えば、
```
Root
...
└Fixed Object(Parent Constraint)(MA World Fixed)
 └Mesh
```
のような構造のアバターがあるとき、
![image](https://github.com/anatawa12/AvatarOptimizer/assets/82163847/97d628be-6e98-4631-8a7e-6940a71b389a)
のようなアニメーションでワールド固定オブジェクトを作ろうとすると、
![image](https://github.com/anatawa12/AvatarOptimizer/assets/82163847/b0e524fe-7159-4fdc-87c5-c782be6240c9)
のように書き換えられ、何故かMeshが偶に原点に位置してしまいます。
~~IsActive使うなと言われればそれまでなのですが~~

**Comment by anatawa12** [comment]
アバターについてもう少し詳しく教えてください。
今回の問題が発生する場合を考えたところ、MeshのIsActiveがonになったと同時にFixed ObjectについたParent Constraintのoffになると考えましたが、そのようにアニメーションを作っていますでしょうか

**Comment by piyoryyta** [comment]
![image](https://github.com/anatawa12/AvatarOptimizer/assets/82163847/fc1f9b2e-392e-4a19-8bac-2ec7bfef8dc3)
0フレーム目にMeshのIsActiveをon、Parent Constraint のActive をoffにしています

**Comment by anatawa12** [comment]
先程リリースしたv1.6.5-rc.3で修正できたと思います。確認よろしくお願いします。

インストールの際にはNDMfのプリリリース版が必要であるため、こちらのドキュメントを参考にしてください。 https://vpm.anatawa12.com/avatar-optimizer/beta/ja/#installation

**Comment by anatawa12** [comment]
返信がなかったため修正完了としてcloseさせていただきます。もしまだ発生するようでしたらopenするようお願いします。
