### ISSUE TITLE
Play時とビルド時でComponentInformationを分けて申告したい

### ISSUE THREAD

**Issue by Narazaka** [anatawa12/AvatarOptimizer#886]
Play時にAv3Emulatorを利用してシーン上のコンポーネントのVRCExpressionsParameter関連値を調整し、Playが終わると同コンポーネントに書き戻して調整完了とする拡張機能を作っています。
https://github.com/Narazaka/AvatarParametersSaver/tree/v3.0.0-alpha.6

このときPlay中はコンポーネントはデータストアとして必要ですが、ビルド時は機能を持たず不要です。

現状は`dependencyCollector.MarkEntrypoint()`でコンポーネントを維持するようにしていますが、ビルド時には不要なのでそのように申告したいところです。

**Comment by anatawa12** [comment]
EditorApplication.isPlayingで切り替えてもAAO的には問題ないのですが特別APIが欲しいということでしょうか？

**Comment by Narazaka** [comment]
あ、ComponentInformationの中でEditorApplication.isPlayingで判定分けて問題ないんですかね。ではそれでもいいかも

**Comment by Narazaka** [comment]
ついでなんですが、「名前を変えない（foo$プリセット設定$12みたいにしない）」的な表明って出来る物でしょうか？

**Comment by anatawa12** [comment]
名前トラックは`ApplySpecialMapping`でTransformのパスを再取得するのが正しいです。

名前の変更ははMergeBoneされると階層が`$`で結合されるのが原因なので、mergeBoneされないようにその親のTransformをdependency宣言すれば回避できます。
AvatarOptimizer内部でも(現状)Humanoid Avatarのパスをなおす機能がないのでHumanoidのボーンとその親boneをdependency宣言してmergeを回避してます

https://github.com/anatawa12/AvatarOptimizer/blob/bc717cf04cea11080e75b743f11ac55572b9b31e/Editor/APIInternal/ComponentInfos.cs#L54-L64

**Comment by Narazaka** [comment]
ありがとうございます。できたっぽいです。

**Comment by Narazaka** [comment]
解決したけどドキュメントにあるとうれしいかも……

**Comment by anatawa12** [comment]
どっちかというと専用の関数はやしたほうが良さそうですね

**Comment by anatawa12** [comment]
パスの話は #889 にするのでこちらはcloseします
