### ISSUE TITLE
Merge Skinned Meshにおいて、m_enabledが全て同じならアニメーションを引き継いで欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [anatawa12/AvatarOptimizer#894]
現状、m_enabledは引き継がれないようになっています。
ですが、同様にアニメーションされている場合は、統合前のmeshを対象に作られたアニメーションを引き継ぐことが(理論上)可能なはずです。

Related: #837

**Comment by anatawa12** [comment]
できはするけど、全部同じかを見て切り替えるだと分かりづらいしチェックボックス生やすのがいいかな

**Comment by anatawa12** [comment]
これ、自動mergeSMRが生えたら需要どんくらいなんだろう

**Comment by Sayamame-beans** [comment]
機能としては依然としてあると嬉しいものだとは思います
(自動MergeSMRだとBlendshapeあるケースで統合されないというのもありますし…)

**Comment by nekobako** [comment]
親が同じ場合のみでもよいので m_IsActive の方も引き継げるとうれしいです。

**Comment by anatawa12** [comment]
optinフラグで実装して違いそうなときはエラーの形で1.8かなぁ

**Comment by anatawa12** [comment]
仕様案

オプションが有効な場合には、以下の条件を満たしていなければエラー
- MergeSkinnedMeshの対象SkinnedMeshRendererのEnabledはアニメーションされていない
- Merge Skinned Meshとソースの共通祖先より下層のアニメーションされているIsActiveまたはEnabledが
  - (それぞれのソース事に)１種類以下
  - ソース事に数に差がない
  - それらが同じ場所(同じクリップの集合)でアニメーションされている

満たされる場合にはそのIsActive / EnabledアニメーションがMergeSkinnedMeshの対象Skinned Mesh RendererのEnabledにコピーされる。
