### ISSUE TITLE
hint内の表記が他と違って気になる

### ISSUE THREAD

**Issue by Sayamame-beans** [anatawa12/AvatarOptimizer#912]
https://github.com/anatawa12/AvatarOptimizer/blob/32410dafc052b5b63d031cfe465d2d77d971489e/.docs/content/docs/tutorial/basic-usage/index.md?plain=1#L83-L96

他の場所では`**`でタイトル表記されているのに、ここだけ`###`なのが気になっています

**Comment by anatawa12** [comment]
アンカーにするためにそうした記憶があります

**Comment by Sayamame-beans** [comment]
あ～～…

**Comment by Sayamame-beans** [comment]
であればまあ、多少表示が違いますが代替案も思いつかないので…
