### ISSUE TITLE
BodyのメッシュをMerge Skinned Meshで作成するとTrace And OptimizeでMMDシェイプキーが削除される

### ISSUE THREAD

**Issue by kurotu** [anatawa12/AvatarOptimizer#939]
### 再現手順
1. アバタールートにBodyオブジェクトを追加する。
2. BodyにMerge Skinned Meshを追加し、MMDシェイプキーを持つほかのメッシュを指定する。
3. Manual BakeしてBodyにMMDシェイプキーがあることを確認する。
4. **Bake前**のアバターにTrace And Optimizeを追加する。すべてデフォルト設定。
5. Manual BakeするとBodyからMMDシェイプキーが削除されている。

### 期待する動作
アバタールート直下のBodyではMMDシェイプキーを削除しない。

実際の利用シーンとして、MAによるキメラ改変時にアバタールート直下にないBody(顔メッシュ)をアバタールート直下に持ってくる用途を想定しています。
再現手順3の後の状態に対してTrace And Optimizeを使用すればMMDシェイプキーを維持できますが、Manual Bakeなしとしたいです。

### 環境
- Avatar Optimizer: 1.9.8
- VRCSDK: 3.5.1
- Unity 2022.3.6f1

**Comment by anatawa12** [comment]
ユースケースがあるのは把握してるのですが、このような使用方法は非対応とする方針になっています

**Comment by kurotu** [comment]
非対応な旨、了解です。確認ありがとうございます。
