### ISSUE TITLE
[1.7.0-beta.1] T&O の FreezeBlendshape で変化するはずのブレンドシェイプが固定される

### ISSUE THREAD

**Issue by nekobako** [anatawa12/AvatarOptimizer#967]
1.7.0-beta.1 の T&O の FreezeBlendshape で、下記のような構成の AnimatorController で変化するはずのブレンドシェイプが固定されます。

- レイヤー 0
  - ステート 0-0 (ブレンドシェイプの値を 0 にする 1 フレームのアニメーション) (WD Off)
- レイヤー 1
  - ステート 1-0 (空のアニメーション) (WD Off)
  - ステート 1-1 (ブレンドシェイプの値を 100 にする 1 フレームのアニメーション) (WD Off)

レイヤー 1 がステート 1-0 のときはブレンドシェイプの値が 0、レイヤー 1 がステート 1-1 のときはブレンドシェイプの値が 100 になる想定です。(表情の干渉防止等で上のレイヤーでリセットするパターン)

T&O の `Skip Freezing Non Animated Blend Shape` にチェックを入れると発生しません。

**Comment by anatawa12** [comment]
再現ができませんでした。もう少し細かい状況を教えていただきたいです、

**Comment by nekobako** [comment]
[967.zip](https://github.com/anatawa12/AvatarOptimizer/files/14805832/967.zip)

Body メッシュに `eye_smile_1` ブレンドシェイプがあるアバターの FX にこちらの AnimatorController を設定すると、T&O なしだと `GestureRight` で `eye_smile_1` ブレンドシェイプが変化しますが、T&O ありだと `eye_smile_1` ブレンドシェイプが 0 で固定され、Body メッシュから消えて変化しなくなります。
別のアバターの別のブレンドシェイプでも試しましたが同様でした。

Animator Parser Debug Window V2 では該当メッシュの該当ブレンドシェイプの項目が `Const:0` になっています。

**Comment by anatawa12** [comment]
ありがとうございます。再現できました。
