### ISSUE TITLE
[1.7.0-beta.1] T&O の Entry/Exit の BlendTree 化が行われないパターン

### ISSUE THREAD

**Issue by nekobako** [anatawa12/AvatarOptimizer#969]
T&O での Entry/Exit の BlendTree 化について、私が Entry/Exit 型だと思っていたものが BlendTree 化されなかったので念のため共有します。
想定と異なる構成であれば Close してください。

- FX_0.controller
  - Entry から全てのステートに Equals で遷移
  - 全てのステートから Exit に NotEquals で遷移
- FX_1.controller
  - Entry からデフォルトステート以外のステートに Equals で遷移
  - 全てのステートから Exit に NotEquals で遷移
- FX_2.controller
  - Entry からデフォルトステート以外のステートに Equals で遷移
  - Entry からデフォルトステートに空の Conditions で遷移 (↑より優先度低)
  - 全てのステートから Exit に NotEquals で遷移
- FX_3.controller
  - Entry からデフォルトステート以外のステートに Equals で遷移
  - デフォルトステートから Exit に Equals で遷移 (デフォルトステート以外のステートの個数分)
  - デフォルトステート以外のステートから Exit に NotEquals で遷移
- FX_4.controller
  - Entry からデフォルトステート以外のステートに Equals で遷移
  - Entry からデフォルトステートに空の Conditions で遷移 (↑より優先度低)
  - デフォルトステートから Exit に Equals で遷移 (デフォルトステート以外のステートの個数分)
  - デフォルトステート以外のステートから Exit に NotEquals で遷移

[Test.zip](https://github.com/anatawa12/AvatarOptimizer/files/14810538/Test.zip)

**Comment by anatawa12** [comment]
FX_0.controller、FX_1.controllerにかんしては変換しても一応問題なさそうですが、GestureLeftが2のときに0 -> 0 -> 0 ->と無限ループになるためあまり想定していませんでした。

FX_2.controller, FX_4.controllerに関しては空のConditionsは想定が大変なため無視していました。Default stateにむける最後のno conditionsは想定して良さそうですね

FX_3.controllerに関しては想定してたはずなので確認します。

**Comment by nekobako** [comment]
たしかにこの組み方、 デフォルトステートに遷移したいときにパラメータの値を 0 にすることと、パラメータが各ステートに対応する値しか取らないことを前提としていますね。。
