### ISSUE TITLE
Merge"Direct"BlendTreeじゃなくなっちゃったので改名する

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/AvatarOptimizer#983]
@anatawa12 Merge"Direct"BlendTreeじゃなくなっちゃいませんか? (コンポーネント名 及び prereleaseでないchangelog など)

_Originally posted by @Sayamame-beans in https://github.com/anatawa12/AvatarOptimizer/issues/980#issuecomment-2036860185_

**Comment by nekobako** [comment]
ぱっと思いついたのは
- MergeBlendTreeLayer
- MergeSingleBlendTreeLayer
- MergeIntoDirectBlendTree

など、、

**Comment by nekobako** [comment]
MA にも MergeBlendTree があるので Layer は付いてたほうが呼ぶときに区別しやすいかもです。
