### ISSUE TITLE
ComponentsのPublic化

### ISSUE THREAD

**Issue by clover0916** [anatawa12/AvatarOptimizer#985]
外部ツールがAvatarOptimizerのComponentsを扱えるようにしてほしいです。

**Comment by anatawa12** [comment]
すべてのコンポーネントを行うと大変なため、必要なコンポーネントを教えていただきたいです。

Related: #976 #832

**Comment by anatawa12** [comment]
完全に #832 とかぶるので必要なコンポーネントについて #832 でコメントしてください

Duplicate of #832
