### ISSUE TITLE
Merge Skinned MeshとMerge ToonLit Materialを組み合わせる場合の説明について言及して欲しい

### ISSUE THREAD

**Issue by mecaota** [anatawa12/AvatarOptimizer#997]
## 概要

Merge Skinned MeshとMerge ToonLit Materialを組み合わせて使う場合、

Merge ToonLit MaterialをどのSkinnedMeshRendererコンポーネントのあるGameObjectに追加すればいいのか、全部に足せばいいのか、Merge Skinned Meshだけ入れれば良いのか分からない

また、Merge ToonLit Materialの対象となるマテリアルが、Merge Skinned Meshによるマテリアル統合が入るので、どれになるのか分からない。

当該Xスレッド https://x.com/negi_VRC_/status/1777659639951139318

## 加筆対象 Merge Skinned Mesh

ここでのマテリアル統合機能はMerge ToonLit Materialには作用しない旨の記載が欲しい

## 加筆対象 Merge ToonLit Material

https://x.com/anatawa12_vrc/status/1777679851501339102

> MergeToonLitMaterialはMergeSkinnedMeshのあるGameObjectに追加するのが想定ですね。

MergeToonLitMaterialとMergeSkinnedMeshを組み合わせて使う場合、MergeSkinnedMeshのあるGameObjectに追加する旨を軽く触れて置くと良さそう

**Comment by anatawa12** [comment]
> Merge ToonLit MaterialをどのSkinnedMeshRendererコンポーネントのあるGameObjectに追加すればいいのか、全部に足せばいいのか、Merge Skinned Meshだけ入れれば良いのか分からない

これはどちらでも動くように設計しているのですよね。なのでどちらも正しいと言えるのがまた難しい
